spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/Users/Gosia/Desktop/PROJEKTY/todo-app/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
  management:
    endpoints:
      web:
        exposure:
          include: '*'

keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true
